run:
  timeout: 3m
  tests: true

linters:
  enable:
    - copyloopvar
    - cyclop
    - deadcode
    - dupl
    - errcheck
    - gocritic
    - godot # doc comment formatting
    - gofmt
    - goimports
    - govet
    - ineffassign
    - predeclared
    - revive
    - staticcheck
    - unparam
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/staranto/tfctlgo
  revive:
    rules:
      - name: dot-imports
      - name: exported
      - name: var-naming
      - name: receiver-naming

  godot:
    scope: all
    period: false

issues:
  exclude-files:
    - ^tools/docgen/.*\.go$
  exclude-rules:
    # Reserved for future, currently no path-specific excludes
